---
title: "1, scraper"
output: html_document
---


```{r message=FALSE, warning=FALSE, include=FALSE}
install.packages('rvest')    # install 'rvest' library in R; library and package are synonyms
install.packages('tidyverse')
install.packages("progress")
```

```{r setup, include=FALSE}
library(rvest)    # a library for web web scraping
library(tidyverse)
library(progress)
```

## Let's code!

```{r}
url <- "https://womensecret.com/es/es/sujetadores?format=ajax&sz=30&start"
content <- read_html(url)
content
```


```{r}
content %>%
  html_nodes("a.c05__name-link.name-link") %>%
  html_text()

```

```{r}
titles <- content %>%
  html_nodes('a.c05__name-link.name-link') %>%
  html_text() %>%
  str_trim()
titles
```

```{r}
price <- content %>%
  html_nodes('span.c05__sales-price.c05__pricing-item') %>%
  html_text() %>%
  str_trim()

price
```

```{r}
df <- data.frame(titles = titles, price = price)

write.csv(df, "womanssecret.csv", row.names = FALSE) 
df

```

```{r}
read.csv("womanssecret.csv")
```

```{r}
npages <- 5  

price <- c()
titles <- c()
links <- c()

url_template <- "https://womensecret.com/es/es/sujetadores?format=ajax&sz=30&start="
```

```{r}
for (page in 0:npages) {
 
  url <- str_c(url_template,
               page * 30)
  
  content <- read_html(url)
  
  
  titles <- content %>%
    html_nodes('a.c05__name-link.name-link') %>%
    html_text() %>%
    str_trim() %>%
    c(titles, .)    
  
  price <- content %>%
    html_nodes('span.c05__sales-price.c05__pricing-item') %>%
    html_text() %>%
    str_trim()  %>%
    c(price, .)
  
  
  links <- content %>%
    html_nodes('a.c05__name-link.name-link') %>%
    html_attr("href") %>%
    c(links, .)
  

  Sys.sleep(3)    
}
```

```{r}
stopifnot(length(dates) == (npages + 1) * 30 &
          length(titles) == (npages + 1) * 30 &
          length(links) == (npages + 1) * 30)

```

```{r}

data.frame(title = titles,
           price = price,
           link = links) %>%
  write.csv("womanssecret.csv",
            row.names = FALSE) 
```

```{r}
df <- read.csv("womanssecret.csv")
df
```
